services:
  - type: web
    name: ecom
    env: python
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn ecom.wsgi:application
    envVars:
      - key: PYTHON_VERSION
        value: 3.11
