# Generated by Django 5.1.5 on 2025-02-27 08:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('web', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='cetegroy',
            new_name='category',
        ),
    ]
